### ISSUE TITLE
Exception response codes

### ISSUE THREAD

**Issue by rob040** [CMB27/ModbusRTUSlave#17]
What Exception response codes have you defined?
They do not appear conforming to the Modbus spec.
The library sourcecode uses magic values, but that keeps them unexplained.

**Comment by CMB27** [comment]
I based the exception response codes on MODBUS Application Protocol Specification V1.1b3 for the function codes that this library supports, which are noted in the README.  I believe these are only function codes 1, 2, 3, and 4.

If you have found a discrepancy between the code and the specification, please indicate the lines of code in which the discrepancy occurs and the relevant document and page of the specification.
