### ISSUE TITLE
Function pointers are not validated

### ISSUE THREAD

**Issue by rob040** [CMB27/ModbusRTUSlave#20]
Class contains 6 function pointers. These pointers aren't zeroed, nor tested before calling. 

Strange things will happen when e.g. no coils are configured and master performs a Modbus Read Coils.

**Comment by CMB27** [comment]
In the 2.0.0 rewrite the library now takes arrays instead of functions. I think this will make it a lot easier to use for everyone. Anyhow, the library does now check if these arrays, which are actually pointers, don't point to 0.

**Comment by CMB27** [comment]
These pointers are now zeroed in the constructor too.
