### ISSUE TITLE
`_numDiscreteRegisters` used instead of `_numInputRegisters`

### ISSUE THREAD

**Issue by gerrygralton** [CMB27/ModbusRTUSlave#23]
There's an error on Line 190 in ModbusRTUSlave.cpp inside the `_processReadInputRegisters()` function. It currently reads:

`  else if (quantity > _numDiscreteInputs || startAddress > (_numInputRegisters - quantity)) _exceptionResponse(2);`

and it should read:

`  else if (quantity > _numInputRegisters || startAddress > (_numInputRegisters - quantity)) _exceptionResponse(2);`

**Comment by CMB27** [comment]
Thank you for pointing out this bug and providing the code to fix it.
