### ISSUE TITLE
USB Serial initialization

### ISSUE THREAD

**Issue by guyhm** [CMB27/ModbusRTUSlave#29]
Great library, all very clear for a simple application.   However I've ran into a problem attempting to read/write modbus over serial over usb.  I am using a Pro Micro clone.  At the PC end I am using qmodmaster.
I can't quite track it down and I was hoping you could shed some light on it.
I have cut down your ModbusRTUSlaveExample.h code so that it just writes a couple of values to the Input Registers and to the Holding Registers, also the one coil is connected to the internal led.
I am not using software serial as i want to use the hardware usb serial. e.g.
ModbusRTUSlave modbus(Serial);

It all works perfectly providing i adopt the following magic spell-

1. Plug in arduino to USB port on PC
2. Open serial port monitor in Arduino IDE
3. Close serial port monitor
4. Connect with qmodmaster 
5. Poll the registers.  All works and the coils work too.

If I miss steps 2 and 3 then the qmodmaster will connect to the port  and I can see the tx/rx leds blink once, but attempting to read or write results in a timeout (even if I extend the timeout period to 1second)
I have tried different serial speeds and configurations with the modbus.begin statement to no avail.   I also tried putting in a Serial.begin statement which didn't help either.
Any ideas please?

Thanks

**Comment by CMB27** [comment]
I am not familiar with qmodmaster. I sounds like the issue is on the computer side. If you find clear evidence that the library itself is causing the issue, let me know, otherwise I can't really help you.
Sorry,
