### ISSUE TITLE
Cannot be used with ESP32

### ISSUE THREAD

**Issue by Richard-2211** [CMB27/ModbusRTUSlave#31]
I tried this library with ESP32 and found it to be incompatible with ESP32. Can you fix it to be compatible with ESP 32?

**Comment by CMB27** [comment]
I updated the library to be compatible with the ESP32.

Make sure to get the library from GitHub. I haven't made a release of these changes yet because they are not tested. These updates are not currently available in the Arduino library manager.

**Comment by Richard-2211** [comment]
Thanks for your respond!
