### ISSUE TITLE
Arduino UNO R4 Minima - was able to receive values, but not send them

### ISSUE THREAD

**Issue by michalpankau** [CMB27/ModbusRTUSlave#35]
Hi Chris,

it has to do something with Stream library - flush returns before write is completed I guess.
With enable pin I had to insert additional delay when going to low with pin.
I implemented a while loop with chartimeout variable in case flush ends too early.
I tested it with my UNO Rev4 minima only and DFRobot RS485 shield (BTW shield in auto mode it works perfectly without any changes to library)

```
void ModbusRTUSlave::_writeResponse(uint8_t len) {
  unsigned long startTime = 0;  
  if (_buf[0] != 0) {
    uint16_t crc = _crc(len);
    _buf[len] = lowByte(crc);
    _buf[len + 1] = highByte(crc);
    if (_dePin != NO_DE_PIN) digitalWrite(_dePin, HIGH);
    startTime = micros();
    _serial->write(_buf, len + 2);
    _serial->flush();
    while (micros() - startTime < (_charTimeout * (len + 2)));
    if (_dePin != NO_DE_PIN) digitalWrite(_dePin, LOW);
    while(_serial->available()) {
      _serial->read();
    }
  }
}
```

Regards,
Michal

**Comment by CMB27** [comment]
Thank you for looking into this.
I appreciate you sharing your findings.

**Comment by rajchips** [comment]
The modified code from Michal works with Nucleo-H753ZI. 
Thanks

**Comment by CMB27** [comment]
I connected an Arduino UNO R4 running the example program to a logic analyzer. I found that the DE pin would always go `LOW` one byte before the last, no matter what the baud rate is.

![PulseViewImage1](https://github.com/CMB27/ModbusRTUSlave/assets/33181265/e48296a1-2ca5-4ae1-b1df-b48abcfee644)

I added
``` C++
#ifdef ARDUINO_ARCH_RENESAS
_flushCompensationDelay = (bitsPerChar * 1000000) / baud;
#endif
```
to `_calculateTimeouts`, and
``` C++
#ifdef ARDUINO_ARCH_RENESAS
delayMicroseconds(_flushCompensationDelay);
#endif
```
just after `_serial->flush();` in `_writeResponse`.
This seems to have solved the issue.

![PulseViewImage2](https://github.com/CMB27/ModbusRTUSlave/assets/33181265/9a2e3794-57ac-4ac4-b433-0c69c82ff92f)

This change may need to be undone in the future if Arduino fixes [Serial.flush()](https://www.arduino.cc/reference/en/language/functions/communication/serial/flush/) to work as documented on the UNO R4.
