### ISSUE TITLE
例子错误

### ISSUE THREAD

**Issue by qq547176052** [CMB27/ModbusRTUSlave#4]
```
invalid conversion from 'char (*)(word)' {aka 'char (*)(unsigned int)'} to 'ModbusRTUSlave::BoolRead' {aka 'signed char (*)(short unsigned int)'} [-fpermissive]

```

![image](https://user-images.githubusercontent.com/26636842/162745604-25279fd2-1fc3-44af-95bd-fb256dcac246.png)

**Comment by CMB27** [comment]
This appears to be one of the example sketches. I am not experiencing this problem with this sketch.
Is the sketch modified in some way?
What board are you using?
