### ISSUE TITLE
Not enough time to transmit a packet with TTL-RS485 and standart Serial

### ISSUE THREAD

**Issue by pr4rt0r** [CMB27/ModbusRTUSlave#5]
![image](https://user-images.githubusercontent.com/106997039/172226569-9e6a03d6-b0d2-4589-8265-b7e45116dd57.png)

**Comment by CMB27** [comment]
Thank you for pointing this out. I added `_serial->flush();` after the `_serial->write(_buf, len + 2);` line. This will cause the program to wait until `_serial` has finished writing.
