### ISSUE TITLE
Question regarding data validation for write single/multiple registers (fc06/fc16)

### ISSUE THREAD

**Issue by kabirwbt** [CMB27/ModbusRTUSlave#54]
Hi,
I want to implement a slave over modbus that only updates the holding register values after validating them and generates a modbus exception(03- Illegal data value(i know this is not as per modbus spec strictly)/ 04 - slave device failure) / does not apply the value to the holding register if the data is out of range.

A use case for this is a modbus compliant thermostat let's say. If I am exposing a holding register for write that controls the set temperature of a thermostat, I have to implement write-protection. I have a modbus compliant thermostat by honeywell that does the same. It generates a illegal data value exception if we attempt to write a temp above a limit as per it's data sheet.

I can modify your code for my own purposes and achieve this. However, I don't see a lot of libraries doing this. What do you think? Should such a feature exist?

**Comment by CMB27** [comment]
I think I actually had this feature in version 1.x.x, but using it involved passing functions to the library for reading and writing values or indicating errors.

My current philosophy is to provide/support a fairly simple library that is easy to use, and will cover about 80% of use cases.

I'm glad you were able to use this library as a starting point for your more specialized application, but I am not interested in adding this feature.
