### ISSUE TITLE
Dependencies broken on PlatformIO

### ISSUE THREAD

**Issue by italo-coelho** [CMB27/ModbusRTUSlave#55]
It seems like there is no dependencies for this library on PlatformIO registry and ModbusRTUComm appears to be necessary for compiling.
![image](https://github.com/user-attachments/assets/32979ee9-f8d3-48a5-9328-54a247cd279d)
![image](https://github.com/user-attachments/assets/82b64ef8-5106-422f-8fd2-052ac8ec1052)

**Comment by CMB27** [comment]
Yes, [ModbusADU](https://github.com/CMB27/ModbusADU) and [ModbusRTUComm](https://github.com/CMB27/ModbusRTUComm) are needed.
It looks like I forgot to note these dependencies in the [library.proprties](https://github.com/CMB27/ModbusRTUSlave/blob/main/library.properties) file.
I have edited the file to properly indicate the dependencies, and I upped the library version to 3.0.1.
This should roll out shortly.

**Comment by italo-coelho** [comment]
Perfect! Thank you.
