### ISSUE TITLE
Answer delay config parameter

### ISSUE THREAD

**Issue by pr4rt0r** [CMB27/ModbusRTUSlave#6]
Could you add a configuration parameter - response delay? The first byte of the response is lost periodicallly.

**Comment by CMB27** [comment]
Okay, feature implemented. Documentation can be found in the [wiki](https://github.com/CMB27/ModbusRTUSlave/wiki/ModbusRTUSlave()). I have also added an [example program](https://github.com/CMB27/ModbusRTUSlave/tree/main/examples/Coil_RS-485) with RS-485, which does include the response delay feature.  
I have not actually tested the feature yet. Please let me know how it works out. I will leave the issue open until you let me know that the feature works, or I have tested it myself.  
Out of curiosity, what hardware are you having an Arduino talk to? It seems to be a little cantankerous.

**Comment by pr4rt0r** [comment]
Thank you very much!!! I can't test right now, unfortunately. It was an arduino nano clone on built-in serial (pin1, 2), 232-485 "arduino" module, moxa 1150 and PC.

**Comment by pr4rt0r** [comment]
Tested successfully
